name: manually build cmake for linux-x86_64

on:
  workflow_dispatch:

jobs:
  linux-x86_64:

    runs-on: ubuntu-latest

    container: alpine:3.16

    steps:
      - run: wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup --use-system-package-manager
      - run: ./ppkg update
      - run: ./ppkg install cmake --link-type=static-only --install-lib=static
      - run: ./ppkg pack    cmake
      - run: cp ~/.ppkg/packed/cmake-*-linux-x86_64.tar.xz .

      - uses: actions/upload-artifact@v3
        with:
          name: cmake---linux-x86_64-tar-xz
          path: cmake-*-linux-x86_64.tar.xz
